# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-auth-service
  template:
    metadata:
      labels:
        app: go-auth-service
    spec:
      containers:
        - name: go-auth-service
          image: denisssssss/go-auth-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: go-auth-service-config
                  key: SERVER_PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: go-auth-service-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: go-auth-service-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: go-auth-service-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: go-auth-service-config
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: go-auth-service-secret
                  key: DB_PASS
---
# Service - ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: go-auth-service
spec:
  type: ClusterIP
  selector:
    app: go-auth-service
  ports:
    - name: go-auth-service
      protocol: TCP
      port: 80
      targetPort: 8000